version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achat
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./
    image: firaskill12/achat-image:1.0.0
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://localhost:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" :  "",
	"spring.jpa.show-sql" : "true",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
 front:
    container_name: front
    build: ./front
    image: mouhamedkl/front:1.0.0
    ports:
    - 4200:80
volumes:
  db :